/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VacanciesRouteImport } from './routes/vacancies'
import { Route as SvarochnyeRabotyRouteImport } from './routes/svarochnye-raboty'
import { Route as MetalloobrabotkaRouteImport } from './routes/metalloobrabotka'
import { Route as ChastnymRouteImport } from './routes/chastnym'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VacanciesRoute = VacanciesRouteImport.update({
  id: '/vacancies',
  path: '/vacancies',
  getParentRoute: () => rootRouteImport,
} as any)
const SvarochnyeRabotyRoute = SvarochnyeRabotyRouteImport.update({
  id: '/svarochnye-raboty',
  path: '/svarochnye-raboty',
  getParentRoute: () => rootRouteImport,
} as any)
const MetalloobrabotkaRoute = MetalloobrabotkaRouteImport.update({
  id: '/metalloobrabotka',
  path: '/metalloobrabotka',
  getParentRoute: () => rootRouteImport,
} as any)
const ChastnymRoute = ChastnymRouteImport.update({
  id: '/chastnym',
  path: '/chastnym',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chastnym': typeof ChastnymRoute
  '/metalloobrabotka': typeof MetalloobrabotkaRoute
  '/svarochnye-raboty': typeof SvarochnyeRabotyRoute
  '/vacancies': typeof VacanciesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chastnym': typeof ChastnymRoute
  '/metalloobrabotka': typeof MetalloobrabotkaRoute
  '/svarochnye-raboty': typeof SvarochnyeRabotyRoute
  '/vacancies': typeof VacanciesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chastnym': typeof ChastnymRoute
  '/metalloobrabotka': typeof MetalloobrabotkaRoute
  '/svarochnye-raboty': typeof SvarochnyeRabotyRoute
  '/vacancies': typeof VacanciesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chastnym'
    | '/metalloobrabotka'
    | '/svarochnye-raboty'
    | '/vacancies'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chastnym' | '/metalloobrabotka' | '/svarochnye-raboty' | '/vacancies'
  id:
    | '__root__'
    | '/'
    | '/chastnym'
    | '/metalloobrabotka'
    | '/svarochnye-raboty'
    | '/vacancies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChastnymRoute: typeof ChastnymRoute
  MetalloobrabotkaRoute: typeof MetalloobrabotkaRoute
  SvarochnyeRabotyRoute: typeof SvarochnyeRabotyRoute
  VacanciesRoute: typeof VacanciesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacancies': {
      id: '/vacancies'
      path: '/vacancies'
      fullPath: '/vacancies'
      preLoaderRoute: typeof VacanciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/svarochnye-raboty': {
      id: '/svarochnye-raboty'
      path: '/svarochnye-raboty'
      fullPath: '/svarochnye-raboty'
      preLoaderRoute: typeof SvarochnyeRabotyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metalloobrabotka': {
      id: '/metalloobrabotka'
      path: '/metalloobrabotka'
      fullPath: '/metalloobrabotka'
      preLoaderRoute: typeof MetalloobrabotkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chastnym': {
      id: '/chastnym'
      path: '/chastnym'
      fullPath: '/chastnym'
      preLoaderRoute: typeof ChastnymRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChastnymRoute: ChastnymRoute,
  MetalloobrabotkaRoute: MetalloobrabotkaRoute,
  SvarochnyeRabotyRoute: SvarochnyeRabotyRoute,
  VacanciesRoute: VacanciesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
